export const DEFECTS_LIST = [
  { code: 1, name: "Agulhado" },
  { code: 2, name: "Bolha de Campana" },
  { code: 3, name: "Bolhas (Peças com ar)" },
  { code: 4, name: "Calibrado" },
  { code: 5, name: "Calibrado Recalcado" },
  { code: 6, name: "Camada de esmalte baixa" },
  { code: 7, name: "Canto quebrado" },
  { code: 8, name: "Casca" },
  { code: 9, name: "Colaminação no esmalte" },
  { code: 10, name: "Descascado" },
  { code: 11, name: "Desperte Calibre" },
  { code: 12, name: "Descarte de bitola" },
  { code: 13, name: "Desenho fora de esquadro" },
  { code: 14, name: "Esmalte fora da linha" },
  { code: 15, name: "Empeno Negativo" },
  { code: 16, name: "Empeno Positivo" },
  { code: 17, name: "Esmalte" },
  { code: 18, name: "Pingo de Gota / Astro" },
  { code: 19, name: "Excesso Positivo (bado)" },
  { code: 20, name: "Falha de Decoração" },
  { code: 21, name: "Falha de Aplicação Astro" },
  { code: 22, name: "Falha de Retífica" },
  { code: 23, name: "Ferido" },
  { code: 24, name: "Fundo do esmalte" },
  { code: 25, name: "Guida de Punção" },
  { code: 26, name: "Guida de Tela" },
  { code: 27, name: "Grumos" },
  { code: 28, name: "Lascado" },
  { code: 29, name: "Lascamento do forno" },
  { code: 30, name: "Metalizado" },
  { code: 31, name: "Peça Estourada do Forno" },
  { code: 32, name: "Pingo de Água" },
  { code: 33, name: "Pingo de tinta" },
  { code: 34, name: "Pingo de Tinta Kerajet" },
  { code: 35, name: "Pinhito" },
  { code: 36, name: "Puxado do forno" },
  { code: 37, name: "Rachado do forno" },
  { code: 38, name: "Remontado do forno" },
  { code: 39, name: "Rebarba de prensa" },
  { code: 40, name: "Repingo de derrete murita" },
  { code: 41, name: "Risco de Campana" },
  { code: 42, name: "Risco de esmalte" },
  { code: 43, name: "Risco de Kerajet" },
  { code: 44, name: "Risco de tela" },
  { code: 45, name: "Sujeira de chama" },
  { code: 46, name: "Sujeira de linha" },
  { code: 47, name: "Sujeira do forno" },
  { code: 48, name: "Tonalidade diferente / mudança" },
  { code: 49, name: "Tonalidade misturada" },
  { code: 50, name: "Trinca" },
  { code: 51, name: "Verruga" }
];
