export const DEFECTS_LIST = [
  { code: 1, name: "Agulhado" },
  { code: 2, name: "Bolha de Campana" },
  { code: 3, name: "Bolhas (peças com ar)" },
  { code: 4, name: "Borrados Rotocollor" },
  { code: 5, name: "Calcário" },
  { code: 6, name: "Camada de esmalte baixa" },
  { code: 7, name: "Canto quebrado" },
  { code: 8, name: "Cascão" },
  { code: 9, name: "Contaminação no Esmalte" },
  { code: 10, name: "Desbocado" },
  { code: 11, name: "Descarte Calibre" },
  { code: 12, name: "Descarte de Bitolas" },
  { code: 13, name: "Desenho fora de Esquadro" },
  { code: 14, name: "Empeno após Falha" },
  { code: 15, name: "Empeno Negativo" },
  { code: 16, name: "Empeno Positivo" },
  { code: 17, name: "Estrias" },
  { code: 18, name: "Pingo de Gota / Astro" },
  { code: 19, name: "Excesso de Protetiva (babado)" },
  { code: 20, name: "Falha de Decoração" },
  { code: 21, name: "Falha de Aplicação Astro" },
  { code: 22, name: "Falha de Protetiva" },
  { code: 23, name: "Fervido" },
  { code: 24, name: "Furos no esmalte" },
  { code: 25, name: "Grudado de Punção" },
  { code: 26, name: "Grudado de Tela" },
  { code: 27, name: "Grumos" },
  { code: 28, name: "Lascado" },
  { code: 29, name: "Lascamento do forno" },
  { code: 30, name: "Martelado" },
  { code: 31, name: "Peça Estourada no Forno" },
  { code: 32, name: "Peças Quebradas" },
  { code: 33, name: "Pingo D'agua" },
  { code: 34, name: "Pingo de tinta" },
  { code: 35, name: "Pingo de Tinta Kerajet" },
  { code: 36, name: "Pirrolho" },
  { code: 37, name: "Raspado do Forno" },
  { code: 38, name: "Remontado no forno" },
  { code: 39, name: "Reprensado de Prensas" },
  { code: 40, name: "Respingo de esmalte - muratura" },
  { code: 41, name: "Risco de Campana" },
  { code: 42, name: "Risco de lâmina" },
  { code: 43, name: "Riscos da kerajet" },
  { code: 44, name: "Sujeira da Chuva" },
  { code: 45, name: "Sujeira de Linha" },
  { code: 46, name: "Sujeira do Forno" },
  { code: 47, name: "Tonalidade (diferença / mudança)" },
  { code: 48, name: "Tonalidade Misturada" },
  { code: 49, name: "Trinca" },
  { code: 50, name: "Trinca do carregamento das prensas" },
  { code: 51, name: "Verruga" }
];

export const SHIFT_HOURS: Record<string, string[]> = {
  A: ['06:00', '07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00'],
  B: ['14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00'],
  C: ['22:00', '23:00', '00:00', '01:00', '02:00', '03:00', '04:00', '05:00'],
  D: ['06:00', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00', '20:00'],
};
